In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
agri_df = pd.read_csv('India Agriculture Crop Production.csv')
agri_df.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296

In [5]:
agri_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345407 entries, 0 to 345406
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             345407 non-null  object
 1   District          345407 non-null  object
 2   Crop              345375 non-null  object
 3   Year              345407 non-null  object
 4   Season            345406 non-null  object
 5   Area              345374 non-null  float64
 6   Area Units        345407 non-null  object
 7   Production        340414 non-null  float64
 8   Production Units  345407 non-null  object
 9   Yield             345374 non-null  float64
dtypes: float64(3), object(7)
memory usage: 26.4+ MB

In [6]:
agri_df.isna().sum()

State                  0
District               0
Crop                  32
Year                   0
Season                 1
Area                  33
Area Units             0
Production          4993
Production Units       0
Yield                 33
dtype: int64

In [7]:
agri_df = agri_df.dropna()
agri_df.isna().sum()

State               0
District            0
Crop                0
Year                0
Season              0
Area                0
Area Units          0
Production          0
Production Units    0
Yield               0
dtype: int64

In [8]:
agri_df.shape

(340414, 10)

###### Unique count and values of Crops, States and Districts

In [9]:
unique_crop_list = agri_df['Crop'].unique()

print(f"Total no of unique crops - {len(unique_crop_list)}")
print(f"We have following unique crops in the dataset- \n{unique_crop_list}")

Total no of unique crops - 56
We have following unique crops in the dataset-
['Arecanut' 'Banana' 'Black pepper' 'Cashewnut' 'Coconut' 'Dry chillies'
 'Ginger' 'Other Kharif pulses' 'other oilseeds' 'Rice' 'Sugarcane'
 'Sweet potato' 'Arhar/Tur' 'Bajra' 'Castor seed' 'Coriander'
 'Cotton(lint)' 'Gram' 'Groundnut' 'Horse-gram' 'Jowar' 'Linseed' 'Maize'
 'Mesta' 'Moong(Green Gram)' 'Niger seed' 'Onion' 'Other Rabi pulses'
 'Potato' 'Ragi' 'Rapeseed &Mustard' 'Safflower' 'Sesamum' 'Small millets'
 'Soyabean' 'Sunflower' 'Tapioca' 'Tobacco' 'Turmeric' 'Urad' 'Wheat'
 'Oilseeds total' 'Jute' 'Masoor' 'Peas & beans (Pulses)' 'Barley'
 'Garlic' 'Khesari' 'Sannhamp' 'Guar seed' 'Moth' 'Cardamom'
 'Other Cereals' 'Cowpea(Lobia)' 'Dry Ginger' 'Other Summer Pulses']

In [10]:
unique_state_list = agri_df['State'].unique()

print(f"Total no of unique state - {len(unique_state_list)}")
print(f"We have following unique state in the dataset- \n{unique_state_list}")

Total no of unique state - 36
We have following unique state in the dataset-
['Andaman and Nicobar Islands' 'Andhra Pradesh' 'Arunachal Pradesh'
 'Assam' 'Bihar' 'Chandigarh' 'Chhattisgarh' 'Dadra and Nagar Haveli'
 'Daman and Diu' 'Delhi' 'Goa' 'Gujarat' 'Haryana' 'Himachal Pradesh'
 'Jammu and Kashmir' 'Jharkhand' 'Karnataka' 'Kerala' 'Madhya Pradesh'
 'Maharashtra' 'Manipur' 'Meghalaya' 'Mizoram' 'Nagaland' 'Odisha'
 'Puducherry' 'Punjab' 'Rajasthan' 'Sikkim' 'Tamil Nadu' 'Tripura'
 'Uttar Pradesh' 'Uttarakhand' 'West Bengal' 'Telangana' 'Laddakh']

In [11]:
unique_district_list = agri_df['District'].unique()

print(f"Total no of unique district - {len(unique_district_list)}")
print(f"We have following unique district in the dataset- \n{unique_district_list}")

Total no of unique district - 728
We have following unique district in the dataset-
['NICOBARS' 'NORTH AND MIDDLE ANDAMAN' 'SOUTH ANDAMANS' 'ANANTAPUR'
 'EAST GODAVARI' 'KRISHNA' 'VIZIANAGARAM' 'WEST GODAVARI' 'ADILABAD'
 'CHITTOOR' 'GUNTUR' 'KADAPA' 'KARIMNAGAR' 'KHAMMAM' 'KURNOOL'
 'MAHBUBNAGAR' 'MEDAK' 'NALGONDA' 'NIZAMABAD' 'PRAKASAM' 'RANGAREDDI'
 'SPSR NELLORE' 'SRIKAKULAM' 'VISAKHAPATANAM' 'WARANGAL' 'CHANGLANG'
 'DIBANG VALLEY' 'EAST KAMENG' 'EAST SIANG' 'KURUNG KUMEY' 'LOHIT'
 'LOWER DIBANG VALLEY' 'LOWER SUBANSIRI' 'PAPUM PARE' 'TAWANG' 'TIRAP'
 'UPPER SIANG' 'UPPER SUBANSIRI' 'WEST KAMENG' 'WEST SIANG' 'BARPETA'
 'BONGAIGAON' 'CACHAR' 'DARRANG' 'DHEMAJI' 'DHUBRI' 'DIBRUGARH'
 'DIMA HASAO' 'GOALPARA' 'GOLAGHAT' 'HAILAKANDI' 'JORHAT' 'KAMRUP'
 'KARBI ANGLONG' 'KARIMGANJ' 'KOKRAJHAR' 'LAKHIMPUR' 'MARIGAON' 'NAGAON'
 'NALBARI' 'SIVASAGAR' 'SONITPUR' 'TINSUKIA' 'ARARIA' 'ARWAL' 'AURANGABAD'
 'BANKA' 'BEGUSARAI' 'BHAGALPUR' 'BHOJPUR' 'BUXAR' 'DARBHANGA' 'GAYA'
 'GOPALGANJ' 'JAMUI' 'JEHANABAD' 'KAIMUR (BHABUA)' 'KATIHAR' 'KHAGARIA'
 'KISHANGANJ' 'LAKHISARAI' 'MADHEPURA' 'MADHUBANI' 'MUNGER' 'MUZAFFARPUR'
 'NALANDA' 'NAWADA' 'PASHCHIM CHAMPARAN' 'PATNA' 'PURBI CHAMPARAN'
 'PURNIA' 'ROHTAS' 'SAHARSA' 'SAMASTIPUR' 'SARAN' 'SHEIKHPURA' 'SHEOHAR'
 'SITAMARHI' 'SIWAN' 'SUPAUL' 'VAISHALI' 'CHANDIGARH' 'BASTAR' 'BILASPUR'
 'DANTEWADA' 'DHAMTARI' 'DURG' 'JANJGIR-CHAMPA' 'JASHPUR' 'KABIRDHAM'
 'KANKER' 'KORBA' 'KOREA' 'MAHASAMUND' 'RAIGARH' 'RAIPUR' 'RAJNANDGAON'
 'SURGUJA' 'DADRA AND NAGAR HAVELI' 'Daman and Diu' 'Delhi' 'Goa'
 'AHMADABAD' 'AMRELI' 'ANAND' 'BANAS KANTHA' 'BHARUCH' 'BHAVNAGAR' 'DANG'
 'DOHAD' 'GANDHINAGAR' 'JAMNAGAR' 'JUNAGADH' 'KHEDA' 'MAHESANA' 'NARMADA'
 'NAVSARI' 'PANCH MAHALS' 'PATAN' 'PORBANDAR' 'RAJKOT' 'SABAR KANTHA'
 'SURAT' 'SURENDRANAGAR' 'VADODARA' 'VALSAD' 'KACHCHH' 'AMBALA' 'BHIWANI'
 'FARIDABAD' 'FATEHABAD' 'GURGAON' 'HISAR' 'JHAJJAR' 'JIND' 'KAITHAL'
 'KARNAL' 'KURUKSHETRA' 'MAHENDRAGARH' 'PANCHKULA' 'PANIPAT' 'REWARI'
 'ROHTAK' 'SIRSA' 'SONIPAT' 'YAMUNANAGAR' 'KANGRA' 'KULLU' 'MANDI'
 'SHIMLA' 'SOLAN' 'UNA' 'CHAMBA' 'HAMIRPUR' 'SIRMAUR' 'KINNAUR'
 'LAHUL AND SPITI' 'DODA' 'JAMMU' 'KATHUA' 'RAJAURI' 'UDHAMPUR' 'KARGIL'
 'LEH LADAKH' 'SRINAGAR' 'BADGAM' 'BARAMULLA' 'POONCH' 'PULWAMA'
 'ANANTNAG' 'KUPWARA' 'CHATRA' 'DUMKA' 'GARHWA' 'GODDA' 'GUMLA'
 'HAZARIBAGH' 'KODERMA' 'LATEHAR' 'LOHARDAGA' 'PAKUR' 'PALAMU' 'RANCHI'
 'SAHEBGANJ' 'SARAIKELA KHARSAWAN' 'SIMDEGA' 'WEST SINGHBHUM' 'BOKARO'
 'DEOGHAR' 'DHANBAD' 'EAST SINGHBUM' 'GIRIDIH' 'JAMTARA' 'BAGALKOT'
 'BANGALORE RURAL' 'BELGAUM' 'BELLARY' 'BENGALURU URBAN' 'CHAMARAJANAGAR'
 'CHIKMAGALUR' 'CHITRADURGA' 'DAKSHIN KANNAD' 'DAVANGERE' 'DHARWAD'
 'GADAG' 'HASSAN' 'HAVERI' 'KODAGU' 'KOLAR' 'MANDYA' 'MYSORE' 'SHIMOGA'
 'TUMKUR' 'UDUPI' 'UTTAR KANNAD' 'BIDAR' 'BIJAPUR' 'GULBARGA' 'KOPPAL'
 'RAICHUR' 'ALAPPUZHA' 'ERNAKULAM' 'IDUKKI' 'KANNUR' 'KASARAGOD' 'KOLLAM'
 'KOTTAYAM' 'KOZHIKODE' 'MALAPPURAM' 'PALAKKAD' 'PATHANAMTHITTA'
 'THIRUVANANTHAPURAM' 'THRISSUR' 'WAYANAD' 'ANUPPUR' 'ASHOKNAGAR'
 'BALAGHAT' 'BARWANI' 'BETUL' 'BHIND' 'BHOPAL' 'BURHANPUR' 'CHHATARPUR'
 'CHHINDWARA' 'DAMOH' 'DATIA' 'DEWAS' 'DHAR' 'DINDORI' 'GUNA' 'GWALIOR'
 'HARDA' 'HOSHANGABAD' 'INDORE' 'JABALPUR' 'JHABUA' 'KATNI' 'KHANDWA'
 'KHARGONE' 'MANDLA' 'MANDSAUR' 'MORENA' 'NARSINGHPUR' 'NEEMUCH' 'PANNA'
 'RAISEN' 'RAJGARH' 'RATLAM' 'REWA' 'SAGAR' 'SATNA' 'SEHORE' 'SEONI'
 'SHAHDOL' 'SHAJAPUR' 'SHEOPUR' 'SHIVPURI' 'SIDHI' 'TIKAMGARH' 'UJJAIN'
 'UMARIA' 'VIDISHA' 'AHMEDNAGAR' 'AKOLA' 'AMRAVATI' 'BEED' 'BHANDARA'
 'BULDHANA' 'CHANDRAPUR' 'DHULE' 'GADCHIROLI' 'GONDIA' 'HINGOLI' 'JALGAON'
 'JALNA' 'KOLHAPUR' 'LATUR' 'NAGPUR' 'NANDED' 'NANDURBAR' 'NASHIK'
 'OSMANABAD' 'PARBHANI' 'PUNE' 'RAIGAD' 'RATNAGIRI' 'SANGLI' 'SATARA'
 'SOLAPUR' 'THANE' 'WARDHA' 'WASHIM' 'YAVATMAL' 'SINDHUDURG' 'SENAPATI'
 'BISHNUPUR' 'CHANDEL' 'CHURACHANDPUR' 'IMPHAL EAST' 'IMPHAL WEST'
 'TAMENGLONG' 'THOUBAL' 'UKHRUL' 'EAST GARO HILLS' 'EAST JAINTIA HILLS'
 'EAST KHASI HILLS' 'RI BHOI' 'SOUTH GARO HILLS' 'WEST GARO HILLS'
 'WEST KHASI HILLS' 'AIZAWL' 'CHAMPHAI' 'KOLASIB' 'LUNGLEI' 'MAMIT'
 'SAIHA' 'DIMAPUR' 'KOHIMA' 'MOKOKCHUNG' 'MON' 'PHEK' 'TUENSANG' 'WOKHA'
 'ZUNHEBOTO' 'ANUGUL' 'BALANGIR' 'BALESHWAR' 'BARGARH' 'BHADRAK' 'BOUDH'
 'CUTTACK' 'DEOGARH' 'DHENKANAL' 'GAJAPATI' 'GANJAM' 'JAGATSINGHAPUR'
 'JAJAPUR' 'JHARSUGUDA' 'KALAHANDI' 'KANDHAMAL' 'KENDRAPARA' 'KENDUJHAR'
 'KHORDHA' 'KORAPUT' 'MALKANGIRI' 'MAYURBHANJ' 'NABARANGPUR' 'NAYAGARH'
 'NUAPADA' 'RAYAGADA' 'SAMBALPUR' 'SONEPUR' 'SUNDARGARH' 'PURI' 'MAHE'
 'PONDICHERRY' 'KARAIKAL' 'YANAM' 'AMRITSAR' 'BATHINDA' 'FARIDKOT'
 'FATEHGARH SAHIB' 'FIROZEPUR' 'HOSHIARPUR' 'JALANDHAR' 'KAPURTHALA'
 'LUDHIANA' 'MOGA' 'MUKTSAR' 'NAWANSHAHR' 'PATIALA' 'RUPNAGAR' 'SANGRUR'
 'MANSA' 'GURDASPUR' 'AJMER' 'ALWAR' 'BANSWARA' 'BARAN' 'BHARATPUR'
 'BHILWARA' 'BIKANER' 'BUNDI' 'CHITTORGARH' 'DAUSA' 'DHOLPUR' 'DUNGARPUR'
 'GANGANAGAR' 'HANUMANGARH' 'JAIPUR' 'JAISALMER' 'JHALAWAR' 'KARAULI'
 'KOTA' 'NAGAUR' 'PALI' 'RAJSAMAND' 'SAWAI MADHOPUR' 'SIKAR' 'SIROHI'
 'TONK' 'UDAIPUR' 'BARMER' 'CHURU' 'JALORE' 'JHUNJHUNU' 'JODHPUR'
 'EAST DISTRICT' 'NORTH DISTRICT' 'SOUTH DISTRICT' 'WEST DISTRICT'
 'COIMBATORE' 'CUDDALORE' 'DHARMAPURI' 'DINDIGUL' 'ERODE' 'KANCHIPURAM'
 'KARUR' 'MADURAI' 'NAMAKKAL' 'PERAMBALUR' 'PUDUKKOTTAI' 'RAMANATHAPURAM'
 'SALEM' 'SIVAGANGA' 'THANJAVUR' 'THENI' 'THIRUVALLUR' 'THIRUVARUR'
 'THOOTHUKUDI' 'TIRUCHIRAPPALLI' 'TIRUNELVELI' 'TIRUVANNAMALAI' 'VELLORE'
 'VILLUPURAM' 'VIRUDHUNAGAR' 'NAGAPATTINAM' 'THE NILGIRIS' 'KANNIYAKUMARI'
 'KRISHNAGIRI' 'DHALAI' 'NORTH TRIPURA' 'SOUTH TRIPURA' 'WEST TRIPURA'
 'AGRA' 'ALIGARH' 'ALLAHABAD' 'AMBEDKAR NAGAR' 'AMROHA' 'AURAIYA'
 'AZAMGARH' 'BAGHPAT' 'BAHRAICH' 'BALLIA' 'BALRAMPUR' 'BANDA' 'BARABANKI'
 'BAREILLY' 'BASTI' 'BIJNOR' 'BUDAUN' 'BULANDSHAHR' 'CHANDAULI'
 'CHITRAKOOT' 'DEORIA' 'ETAH' 'ETAWAH' 'FAIZABAD' 'FARRUKHABAD' 'FATEHPUR'
 'FIROZABAD' 'GAUTAM BUDDHA NAGAR' 'GHAZIABAD' 'GHAZIPUR' 'GONDA'
 'GORAKHPUR' 'HARDOI' 'HATHRAS' 'JALAUN' 'JAUNPUR' 'JHANSI' 'KANNAUJ'
 'KANPUR DEHAT' 'KANPUR NAGAR' 'KAUSHAMBI' 'KHERI' 'KUSHI NAGAR'
 'LALITPUR' 'LUCKNOW' 'MAHARAJGANJ' 'MAHOBA' 'MAINPURI' 'MATHURA' 'MAU'
 'MEERUT' 'MIRZAPUR' 'MORADABAD' 'MUZAFFARNAGAR' 'PILIBHIT' 'PRATAPGARH'
 'RAE BARELI' 'RAMPUR' 'SAHARANPUR' 'SANT KABEER NAGAR'
 'SANT RAVIDAS NAGAR' 'SHAHJAHANPUR' 'SHRAVASTI' 'SIDDHARTH NAGAR'
 'SITAPUR' 'SONBHADRA' 'SULTANPUR' 'UNNAO' 'VARANASI' 'CHAMOLI'
 'CHAMPAWAT' 'DEHRADUN' 'HARIDWAR' 'NAINITAL' 'PAURI GARHWAL'
 'PITHORAGARH' 'RUDRA PRAYAG' 'TEHRI GARHWAL' 'UDAM SINGH NAGAR'
 'UTTAR KASHI' 'ALMORA' 'BAGESHWAR' '24 PARAGANAS NORTH'
 '24 PARAGANAS SOUTH' 'BANKURA' 'BIRBHUM' 'COOCHBEHAR' 'DARJEELING'
 'DINAJPUR DAKSHIN' 'DINAJPUR UTTAR' 'HOOGHLY' 'HOWRAH' 'JALPAIGURI'
 'MALDAH' 'MEDINIPUR EAST' 'MEDINIPUR WEST' 'MURSHIDABAD' 'NADIA'
 'PURBA BARDHAMAN' 'PURULIA' 'ANJAW' 'BAKSA' 'CHIRANG' 'KAMRUP METRO'
 'UDALGURI' 'NARAYANPUR' 'NORTH GOA' 'SOUTH GOA' 'MEWAT' 'PALGHAR'
 'LAWNGTLAI' 'SERCHHIP' 'S' 'TARN TARAN' 'Andaman and Nicobar Islands'
 'DELHI_TOTAL' 'TAPI' 'PALWAL' 'REASI' 'SAMBA' 'KISHTWAR' 'RAMBAN'
 'KULGAM' 'BANDIPORA' 'GANDERBAL' 'SHOPIAN' 'KHUNTI' 'RAMGARH'
 'RAMANAGARA' 'CHIKBALLAPUR' 'ALIRAJPUR' 'SINGRAULI' 'KIPHIRE' 'LONGLENG'
 'PEREN' 'BARNALA' 'TIRUPPUR' 'ARIYALUR' 'KASGANJ' 'BALOD' 'BALODA BAZAR'
 'BEMETARA' 'GARIYABAND' 'KONDAGAON' 'MUNGELI' 'SUKMA' 'SURAJPUR' 'YADGIR'
 'FAZILKA' 'PATHANKOT' 'GOMATI' 'KHOWAI' 'SEPAHIJALA' 'UNAKOTI' 'AMETHI'
 'HAPUR' 'SAMBHAL' 'SHAMLI' 'KRA DAADI' 'LONGDING' 'NAMSAI' 'SIANG' 'DIU'
 'DAMAN' 'ARAVALLI' 'BOTAD' 'CHHOTAUDEPUR' 'GIR SOMNATH' 'MAHISAGAR'
 'DEVBHUMI DWARKA' 'MORBI' 'CHARKI DADRI' 'AGAR MALWA' 'NORTH GARO HILLS'
 'SOUTH WEST GARO HILLS' 'SOUTH WEST KHASI HILLS' 'WEST JAINTIA HILLS'
 'ALIPURDUAR' 'KAMLE' 'LOWER SIANG' 'MUMBAI SUBURBAN' 'BHADRADRI'
 'JAGITIAL' 'JANGOAN' 'JAYASHANKAR' 'JOGULAMBA' 'KAMAREDDY'
 'KOMARAM BHEEM ASIFABAD' 'MAHABUBABAD' 'MANCHERIAL' 'MEDCHAL' 'MULUGU'
 'NAGARKURNOOL' 'NARAYANAPET' 'NIRMAL' 'PEDDAPALLI' 'RAJANNA' 'SANGAREDDY'
 'SIDDIPET' 'SURYAPET' 'VIKARABAD' 'WANAPARTHY' 'WARANGAL URBAN' 'YADADRI'
 'JHARGRAM' 'PASCHIM BARDHAMAN' 'KALIMPONG' 'LEPARADA' 'PAKKE KESSANG'
 'SHI YOMI' 'BISWANATH' 'CHARAIDEO' 'HOJAI' 'MAJULI'
 'SOUTH SALMARA MANCACHAR' 'WEST KARBI ANGLONG' 'GAURELLA-PENDRA-MARWAHI'
 'BAGALKOTE' 'BALLARI' 'BELAGAVI' 'CHAMARAJANAGARA' 'CHIKKABALLAPURA'
 'CHIKKAMAGALURU' 'DAKSHINA KANNADA' 'MYSURU' 'SHIVAMOGGA' 'TUMAKURU'
 'UTTARA KANNADA' 'VIJAYAPURA' 'KALABURAGI' 'YADAGIRI' 'NIWARI'
 'SHAHID BHAGAT SINGH NAGAR' 'TUTICORIN' 'CHENNAI' 'KALLAKURICHI'
 'TENKASI' 'TIRUPATHUR' 'CHENGALPATTU' 'RANIPET' 'HANUMAKONDA'
 'MEDCHAL MALKAJGIRI' 'HYDERABAD' 'MUMBAI']

In [12]:
agri_df['Production Units'].unique()

array(['Tonnes', 'Nuts', 'Bales'], dtype=object)

In [13]:
agri_df[agri_df['Production Units'] == 'Nuts']['Crop'].unique()

array(['Coconut'], dtype=object)

In [14]:
def unit_standardization(df):
    if df['Production Units'] == 'Nuts':
        return np.round(df['Production']/50,1)
    elif df['Production Units'] == 'Tonnes':
        return df['Production']
    else:
        return np.round(df['Production']/4.5929637955183,1)

In [15]:
agri_df['New Production'] = agri_df.apply(unit_standardization,axis=1)

In [16]:
agri_df.drop(columns=['Production','Production Units'],inplace=True)

In [17]:
agri_df.head(3)

,State,District,Crop,Year,Season,Area,Area Units,Yield,New Production
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,1.643541,2061.0
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,1.655803,2083.0
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1.209358,1525.0

In [18]:
#Which are the top 5 most common crops in India

agri_df['Crop'].value_counts().head()

Crop
Rice                 21573
Maize                20329
Moong(Green Gram)    14813
Urad                 14389
Sesamum              12744
Name: count, dtype: int64

In [19]:
#Get statewise total production of crops
total_production_list = []
for state in unique_state_list:
    total_production_list.append(agri_df.loc[agri_df['State'] == state, 'New Production'].sum())

In [20]:
crop_production_df = pd.DataFrame({
    'State' : unique_state_list,
    'Total Crop Production' : total_production_list
})
crop_production_df.sort_values('Total Crop Production',ascending=False).head()

            State  Total Crop Production
31  Uttar Pradesh           4.442549e+09
17         Kerala           2.685620e+09
29     Tamil Nadu           2.563320e+09
16      Karnataka           2.316390e+09
19    Maharashtra           1.790382e+09

### Highest producer of Rice since 1997

In [21]:
agri_rice_df = agri_df[agri_df['Crop'] == 'Rice']
unique_rice_growing_states = agri_rice_df['State'].unique()

total_rice_production = []
for state in unique_rice_growing_states:
    total_rice_production.append(np.round(agri_rice_df.loc[agri_rice_df['State'] == state, 'New Production'].sum(),2))

In [22]:
rice_production_df = pd.DataFrame({
    'State' : unique_rice_growing_states,
    'Total Rice Production' : total_rice_production
})

In [23]:
rice_production_df.sort_values('Total Rice Production',ascending=False).head()

             State  Total Rice Production
33     West Bengal            338984869.0
31   Uttar Pradesh            296108280.0
26          Punjab            243042000.0
1   Andhra Pradesh            239361201.0
24          Odisha            153257182.0

###### Best year for Agriculture

In [24]:
unique_year_list = agri_df['Year'].unique()

In [25]:
unique_year_list

array(['2001-02', '2002-03', '2003-04', '2004-05', '2006-07', '2005-06',
       '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13',
       '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19',
       '2019-20', '2020-21', '2000-01', '1997-98', '1998-99', '1999-00'],
      dtype=object)

In [26]:
yearly_production_list = []
for year in unique_year_list:
    yearly_production_list.append(agri_df.loc[agri_df['Year']==year, 'New Production'].sum())

In [27]:
yearly_production_df = pd.DataFrame(
{
    'year' : unique_year_list,
    'total crop production' : yearly_production_list
})
yearly_production_df.sort_values('total crop production', ascending=False).head()

       year  total crop production
18  2019-20           1.201999e+09
17  2018-19           1.179830e+09
16  2017-18           1.129270e+09
10  2011-12           1.090406e+09
13  2014-15           1.085326e+09